/**
 * Strings of the @rcene/kit/app blocks (keys "kit.app.*" or "kit.<block>.*").
 * English is the source; Waray and Filipino are AI drafts listed in
 * rcene/i18n/REVIEW.md. Merged into kitStrings by rcene/kit/i18n.ts.
 *
 * Only chrome lives here (buttons, captions, state words, validation
 * messages). Titles, labels and data come in through props, already
 * translated by the app.
 */
export const appStrings = {
  en: {
    // PageHeader
    "kit.pageHeader.breadcrumbs": "You are here",
    // ConsoleLayout
    "kit.console.nav": "Sections",
    "kit.console.menu": "Menu",
    "kit.console.aside": "Side panel",
    // BoardShell / BoardRotator
    "kit.board.timeNow": "Time now",
    "kit.board.pages": "Board pages",
    "kit.board.page": "Page {n} of {total}",
    "kit.board.pause": "Pause",
    "kit.board.play": "Play",
    "kit.board.paused": "Paused",
    "kit.board.previous": "Previous page",
    "kit.board.next": "Next page",
    // DataTable
    "kit.table.search": "Search the table",
    "kit.table.searchPlaceholder": "Search…",
    "kit.table.clearSearch": "Clear search",
    "kit.table.page": "Page {n} of {total}",
    "kit.table.previous": "Previous page",
    "kit.table.next": "Next page",
    "kit.table.showing": "Showing {from}–{to} of {total}",
    "kit.table.download": "Download CSV",
    "kit.table.empty": "No rows to show yet.",
    "kit.table.noMatches": "No rows match “{query}”.",
    "kit.table.rowHint": "Press Enter on a row to open it.",
    // ChartCard
    "kit.chart.view": "Show as",
    "kit.chart.chart": "Chart",
    "kit.chart.table": "Table",
    "kit.chart.note": "Note",
    // Wizard
    "kit.wizard.progress": "Progress",
    "kit.wizard.step": "Step {n} of {total}",
    "kit.wizard.back": "Back",
    "kit.wizard.next": "Next",
    "kit.wizard.finish": "Finish",
    "kit.wizard.done": "(done)",
    "kit.wizard.cannotNext": "Fill in the required fields to continue.",
    // StatusTimeline
    "kit.timeline.label": "Status timeline",
    "kit.timeline.done": "Done",
    "kit.timeline.current": "In progress",
    "kit.timeline.upcoming": "Upcoming",
    "kit.timeline.blocked": "Blocked",
    // CapacityMeter
    "kit.capacity.open": "Open",
    "kit.capacity.nearlyFull": "Nearly full",
    "kit.capacity.full": "Full",
    "kit.capacity.over": "Over capacity",
    "kit.capacity.valueText": "{value} of {max} — {state}",
    "kit.capacity.left": "{n} left",
    "kit.capacity.overBy": "{n} over",
    // Form fields
    "kit.form.required": "(required)",
    "kit.form.choose": "Choose…",
    "kit.form.barangay": "Choose a barangay",
    "kit.form.barangaySearch": "Search barangays…",
    "kit.form.barangayNone": "No barangay matches.",
    "kit.form.charCount": "{count} of {max} characters",
    // kitZodErrors
    "kit.form.error.required": "This is required.",
    "kit.form.error.tooShort": "Use at least {min} characters.",
    "kit.form.error.tooLong": "Use at most {max} characters.",
    "kit.form.error.number": "Enter a number.",
    "kit.form.error.wholeNumber": "Enter a whole number.",
    "kit.form.error.min": "Enter {min} or more.",
    "kit.form.error.max": "Enter {max} or less.",
    "kit.form.error.above": "Enter a number above {min}.",
    "kit.form.error.below": "Enter a number below {max}.",
    "kit.form.error.multipleOf": "Use steps of {step}.",
    "kit.form.error.email": "Enter a valid email address.",
    "kit.form.error.format": "Check the format.",
    "kit.form.error.choose": "Choose one of the options.",
    "kit.form.error.chooseAtLeast": "Choose at least {min}.",
    "kit.form.error.chooseAtMost": "Choose at most {max}.",
    "kit.form.error.invalid": "Check this value.",
    // QrDisplay
    "kit.qr.alt": "QR code: {label}",
    "kit.qr.loading": "Making the QR code…",
    "kit.qr.error": "Could not make the QR code.",
    "kit.qr.downloadPng": "Download PNG",
    "kit.qr.downloadSvg": "Download SVG",
  },
  war: {
    "kit.pageHeader.breadcrumbs": "Aadi ka",
    "kit.console.nav": "Mga seksyon",
    "kit.console.menu": "Menu",
    "kit.console.aside": "Panel ha kilid",
    "kit.board.timeNow": "Oras yana",
    "kit.board.pages": "Mga pahina han board",
    "kit.board.page": "Pahina {n} han {total}",
    "kit.board.pause": "Pundoha",
    "kit.board.play": "Padayona",
    "kit.board.paused": "Naka-pundo",
    "kit.board.previous": "Naglabay nga pahina",
    "kit.board.next": "Sunod nga pahina",
    "kit.table.search": "Bilnga ha talaan",
    "kit.table.searchPlaceholder": "Bilnga…",
    "kit.table.clearSearch": "Panasa an ginbibiling",
    "kit.table.page": "Pahina {n} han {total}",
    "kit.table.previous": "Naglabay nga pahina",
    "kit.table.next": "Sunod nga pahina",
    "kit.table.showing": "Ginpapakita an {from}–{to} han {total}",
    "kit.table.download": "I-download an CSV",
    "kit.table.empty": "Waray pa linya nga maipakita.",
    "kit.table.noMatches": "Waray linya nga angay ha “{query}”.",
    "kit.table.rowHint": "Pinduta an Enter ha usa nga linya basi ablihon ini.",
    "kit.chart.view": "Ipakita sugad nga",
    "kit.chart.chart": "Tsart",
    "kit.chart.table": "Talaan",
    "kit.chart.note": "Pahinumdom",
    "kit.wizard.progress": "Pag-uswag",
    "kit.wizard.step": "Lakang {n} han {total}",
    "kit.wizard.back": "Balik",
    "kit.wizard.next": "Sunod",
    "kit.wizard.finish": "Tapusa",
    "kit.wizard.done": "(human na)",
    "kit.wizard.cannotNext": "Pun-a an mga kinahanglan nga field basi makapadayon.",
    "kit.timeline.label": "Timeline han kahimtang",
    "kit.timeline.done": "Human na",
    "kit.timeline.current": "Ginbubuhat pa",
    "kit.timeline.upcoming": "Maabot pa",
    "kit.timeline.blocked": "Napugngan",
    "kit.capacity.open": "Bukas",
    "kit.capacity.nearlyFull": "Hapit na puno",
    "kit.capacity.full": "Puno na",
    "kit.capacity.over": "Sobra ha kapasidad",
    "kit.capacity.valueText": "{value} han {max} — {state}",
    "kit.capacity.left": "{n} pa an bakante",
    "kit.capacity.overBy": "Sobra hin {n}",
    "kit.form.required": "(kinahanglan)",
    "kit.form.choose": "Pili…",
    "kit.form.barangay": "Pili hin barangay",
    "kit.form.barangaySearch": "Bilnga an barangay…",
    "kit.form.barangayNone": "Waray barangay nga angay.",
    "kit.form.charCount": "{count} han {max} nga letra",
    "kit.form.error.required": "Kinahanglan ini.",
    "kit.form.error.tooShort": "Gamita in diri maubos hin {min} nga letra.",
    "kit.form.error.tooLong": "Tubtob {max} nga letra la.",
    "kit.form.error.number": "Pagbutang hin numero.",
    "kit.form.error.wholeNumber": "Pagbutang hin bug-os nga numero.",
    "kit.form.error.min": "Pagbutang hin {min} o labaw pa.",
    "kit.form.error.max": "Pagbutang hin {max} o ubos pa.",
    "kit.form.error.above": "Pagbutang hin numero nga labaw ha {min}.",
    "kit.form.error.below": "Pagbutang hin numero nga ubos ha {max}.",
    "kit.form.error.multipleOf": "Gamita an lakang nga {step}.",
    "kit.form.error.email": "Pagbutang hin husto nga email address.",
    "kit.form.error.format": "Kitaa an format.",
    "kit.form.error.choose": "Pili hin usa ha mga pagpipilian.",
    "kit.form.error.chooseAtLeast": "Pili hin diri maubos hin {min}.",
    "kit.form.error.chooseAtMost": "Pili hin tubtob {max}.",
    "kit.form.error.invalid": "Kitaa ini nga bili.",
    "kit.qr.alt": "QR code: {label}",
    "kit.qr.loading": "Ginhihimo an QR code…",
    "kit.qr.error": "Diri mahimo an QR code.",
    "kit.qr.downloadPng": "I-download an PNG",
    "kit.qr.downloadSvg": "I-download an SVG",
  },
  fil: {
    "kit.pageHeader.breadcrumbs": "Nasaan ka",
    "kit.console.nav": "Mga seksiyon",
    "kit.console.menu": "Menu",
    "kit.console.aside": "Panel sa gilid",
    "kit.board.timeNow": "Oras ngayon",
    "kit.board.pages": "Mga pahina ng board",
    "kit.board.page": "Pahina {n} ng {total}",
    "kit.board.pause": "I-pause",
    "kit.board.play": "Ituloy",
    "kit.board.paused": "Naka-pause",
    "kit.board.previous": "Nakaraang pahina",
    "kit.board.next": "Susunod na pahina",
    "kit.table.search": "Maghanap sa talahanayan",
    "kit.table.searchPlaceholder": "Maghanap…",
    "kit.table.clearSearch": "Burahin ang hinahanap",
    "kit.table.page": "Pahina {n} ng {total}",
    "kit.table.previous": "Nakaraang pahina",
    "kit.table.next": "Susunod na pahina",
    "kit.table.showing": "Ipinapakita ang {from}–{to} sa {total}",
    "kit.table.download": "I-download ang CSV",
    "kit.table.empty": "Wala pang hilerang maipapakita.",
    "kit.table.noMatches": "Walang hilerang tugma sa “{query}”.",
    "kit.table.rowHint": "Pindutin ang Enter sa isang hilera para buksan ito.",
    "kit.chart.view": "Ipakita bilang",
    "kit.chart.chart": "Tsart",
    "kit.chart.table": "Talahanayan",
    "kit.chart.note": "Paalala",
    "kit.wizard.progress": "Pag-usad",
    "kit.wizard.step": "Hakbang {n} sa {total}",
    "kit.wizard.back": "Bumalik",
    "kit.wizard.next": "Susunod",
    "kit.wizard.finish": "Tapusin",
    "kit.wizard.done": "(tapos na)",
    "kit.wizard.cannotNext": "Punan ang mga kailangang field para magpatuloy.",
    "kit.timeline.label": "Timeline ng katayuan",
    "kit.timeline.done": "Tapos na",
    "kit.timeline.current": "Kasalukuyan",
    "kit.timeline.upcoming": "Paparating",
    "kit.timeline.blocked": "Naharang",
    "kit.capacity.open": "Bukas",
    "kit.capacity.nearlyFull": "Halos puno na",
    "kit.capacity.full": "Puno na",
    "kit.capacity.over": "Lampas sa kapasidad",
    "kit.capacity.valueText": "{value} sa {max} — {state}",
    "kit.capacity.left": "{n} pa ang bakante",
    "kit.capacity.overBy": "Sobra ng {n}",
    "kit.form.required": "(kailangan)",
    "kit.form.choose": "Pumili…",
    "kit.form.barangay": "Pumili ng barangay",
    "kit.form.barangaySearch": "Maghanap ng barangay…",
    "kit.form.barangayNone": "Walang tugmang barangay.",
    "kit.form.charCount": "{count} sa {max} na titik",
    "kit.form.error.required": "Kailangan ito.",
    "kit.form.error.tooShort": "Gumamit ng hindi bababa sa {min} na titik.",
    "kit.form.error.tooLong": "Hanggang {max} na titik lamang.",
    "kit.form.error.number": "Maglagay ng numero.",
    "kit.form.error.wholeNumber": "Maglagay ng buong numero.",
    "kit.form.error.min": "Maglagay ng {min} o higit pa.",
    "kit.form.error.max": "Maglagay ng {max} o mas mababa.",
    "kit.form.error.above": "Maglagay ng numerong higit sa {min}.",
    "kit.form.error.below": "Maglagay ng numerong mas mababa sa {max}.",
    "kit.form.error.multipleOf": "Gumamit ng hakbang na {step}.",
    "kit.form.error.email": "Maglagay ng tamang email address.",
    "kit.form.error.format": "Suriin ang format.",
    "kit.form.error.choose": "Pumili ng isa sa mga opsiyon.",
    "kit.form.error.chooseAtLeast": "Pumili ng hindi bababa sa {min}.",
    "kit.form.error.chooseAtMost": "Pumili ng hanggang {max}.",
    "kit.form.error.invalid": "Suriin ang halagang ito.",
    "kit.qr.alt": "QR code: {label}",
    "kit.qr.loading": "Ginagawa ang QR code…",
    "kit.qr.error": "Hindi magawa ang QR code.",
    "kit.qr.downloadPng": "I-download ang PNG",
    "kit.qr.downloadSvg": "I-download ang SVG",
  },
} satisfies { en: Record<string, string>; war: Record<string, string>; fil: Record<string, string> };

/** Every key of the app family's strings (what `kitZodErrors` and the blocks look up). */
export type AppStringKey = keyof typeof appStrings.en;
