/**
 * Strings of the @rcene/kit/poster blocks (keys "kit.poster.*" or "kit.<block>.*").
 * English is the source; Waray and Filipino are AI drafts listed in
 * rcene/i18n/REVIEW.md. Merged into kitStrings by rcene/kit/i18n.ts.
 */
export const posterStrings = {
  en: {
    "kit.poster.sheet": "Poster",
    "kit.poster.toolbar": "Poster tools",
    "kit.poster.size": "Paper size",
    "kit.poster.orientation": "Orientation",
    "kit.poster.portrait": "Portrait",
    "kit.poster.landscape": "Landscape",
    "kit.poster.scale": "Preview at {percent}",
    "kit.poster.printHint": "In the print dialog: Margins None, Background graphics on.",
    "kit.poster.overflow": "Some content runs past the edge of the sheet and will be cut off in print. Shorten the text or make the picture smaller.",
    "kit.poster.panel.problem": "The problem",
    "kit.poster.panel.picture": "The app in one picture",
    "kit.poster.panel.different": "What's different",
    "kit.poster.panel.ai": "How AI built it",
    "kit.poster.panel.data": "Data",
    "kit.poster.panel.impact": "Impact",
    "kit.printButton.label": "Print",
    "kit.posterFigure.download": "Download SVG",
    "kit.posterFigure.source": "Source: {source}",
    "kit.aiBuilt.tools": "AI tools",
    "kit.aiBuilt.steps": "How we worked",
    "kit.aiBuilt.disclosureLabel": "Disclosure",
    "kit.aiBuilt.disclosure":
      "Built before the event, with AI coding assistants: the data, the shared libraries and the starter apps. Everything built on the day is in the git history after the pre-event-freeze tag.",
    "kit.qrToApp.label": "Scan to open the app",
    "kit.qrToApp.alt": "QR code that opens {url}",
    "kit.presenter.region": "Presenter",
    "kit.presenter.step": "Step {n} of {total}",
    "kit.presenter.announce": "Step {n} of {total}: {caption}",
    "kit.presenter.next": "Next step",
    "kit.presenter.back": "Previous step",
    "kit.presenter.hide": "Hide presenter bar",
    "kit.presenter.timerStart": "Start timer",
    "kit.presenter.timerPause": "Pause timer",
    "kit.presenter.timerReset": "Reset timer",
    "kit.presenter.elapsed": "Elapsed time",
    "kit.presenter.left": "{time} left",
    "kit.presenter.over": "{time} over",
    "kit.presenter.keys": "→ next · ← back · T timer · P bar · Esc hide",
    "kit.presenter.notesKeys": "→ next · ← back · T timer",
    "kit.presenter.notesTitle": "Presenter notes",
    "kit.presenter.notes": "Speaker notes",
    "kit.presenter.noNotes": "No notes for this step.",
    "kit.presenter.upNext": "Up next",
    "kit.presenter.end": "End of the demo",
  },
  war: {
    "kit.poster.sheet": "Poster",
    "kit.poster.toolbar": "Mga gamit han poster",
    "kit.poster.size": "Kadako han papel",
    "kit.poster.orientation": "Oryentasyon",
    "kit.poster.portrait": "Patindog",
    "kit.poster.landscape": "Pahigda",
    "kit.poster.scale": "Silip ha {percent}",
    "kit.poster.printHint": "Ha print dialog: Margins None, i-on an Background graphics.",
    "kit.poster.overflow": "May sulod nga lumalapaw ha sidsid han papel ngan mauutod ha pag-print. Pamub-a an teksto o pagamaya an litrato.",
    "kit.poster.panel.problem": "An problema",
    "kit.poster.panel.picture": "An app ha usa nga litrato",
    "kit.poster.panel.different": "Ano an iba",
    "kit.poster.panel.ai": "Paonan-o ini ginhimo han AI",
    "kit.poster.panel.data": "Datos",
    "kit.poster.panel.impact": "Epekto",
    "kit.printButton.label": "I-print",
    "kit.posterFigure.download": "I-download an SVG",
    "kit.posterFigure.source": "Tinikangan: {source}",
    "kit.aiBuilt.tools": "Mga gamit nga AI",
    "kit.aiBuilt.steps": "Paonan-o kami nagtrabaho",
    "kit.aiBuilt.disclosureLabel": "Pagpahayag",
    "kit.aiBuilt.disclosure":
      "Ginhimo antes han event, upod an mga AI coding assistant: an datos, an mga shared library ngan an mga panguna nga app. An ngatanan nga ginhimo ha mismo nga adlaw aada ha git history kahuman han tag nga pre-event-freeze.",
    "kit.qrToApp.label": "I-scan para ablihan an app",
    "kit.qrToApp.alt": "QR code nga nag-aabri han {url}",
    "kit.presenter.region": "Presenter",
    "kit.presenter.step": "Lakang {n} han {total}",
    "kit.presenter.announce": "Lakang {n} han {total}: {caption}",
    "kit.presenter.next": "Sunod nga lakang",
    "kit.presenter.back": "Naglabay nga lakang",
    "kit.presenter.hide": "Tagoa an presenter bar",
    "kit.presenter.timerStart": "Sugdi an timer",
    "kit.presenter.timerPause": "Ihunong anay an timer",
    "kit.presenter.timerReset": "I-reset an timer",
    "kit.presenter.elapsed": "Naglabay nga oras",
    "kit.presenter.left": "{time} an nabilin",
    "kit.presenter.over": "Sobra hin {time}",
    "kit.presenter.keys": "→ sunod · ← balik · T timer · P bar · Esc tagoa",
    "kit.presenter.notesKeys": "→ sunod · ← balik · T timer",
    "kit.presenter.notesTitle": "Mga nota han presenter",
    "kit.presenter.notes": "Mga nota han nagyayakan",
    "kit.presenter.noNotes": "Waray nota para hini nga lakang.",
    "kit.presenter.upNext": "Sunod",
    "kit.presenter.end": "Katapusan han demo",
  },
  fil: {
    "kit.poster.sheet": "Poster",
    "kit.poster.toolbar": "Mga kasangkapan ng poster",
    "kit.poster.size": "Laki ng papel",
    "kit.poster.orientation": "Oryentasyon",
    "kit.poster.portrait": "Patayo",
    "kit.poster.landscape": "Pahiga",
    "kit.poster.scale": "Silip sa {percent}",
    "kit.poster.printHint": "Sa print dialog: Margins None, naka-on ang Background graphics.",
    "kit.poster.overflow": "May nilalamang lumalampas sa gilid ng papel at mapuputol sa pag-print. Paikliin ang teksto o paliitin ang larawan.",
    "kit.poster.panel.problem": "Ang problema",
    "kit.poster.panel.picture": "Ang app sa isang larawan",
    "kit.poster.panel.different": "Ano ang naiiba",
    "kit.poster.panel.ai": "Paano ito binuo ng AI",
    "kit.poster.panel.data": "Datos",
    "kit.poster.panel.impact": "Epekto",
    "kit.printButton.label": "I-print",
    "kit.posterFigure.download": "I-download ang SVG",
    "kit.posterFigure.source": "Pinagmulan: {source}",
    "kit.aiBuilt.tools": "Mga AI tool",
    "kit.aiBuilt.steps": "Paano kami nagtrabaho",
    "kit.aiBuilt.disclosureLabel": "Pagsisiwalat",
    "kit.aiBuilt.disclosure":
      "Binuo bago ang event, gamit ang mga AI coding assistant: ang datos, ang mga shared library at ang mga panimulang app. Ang lahat ng binuo sa mismong araw ay nasa git history pagkatapos ng tag na pre-event-freeze.",
    "kit.qrToApp.label": "I-scan para buksan ang app",
    "kit.qrToApp.alt": "QR code na nagbubukas ng {url}",
    "kit.presenter.region": "Presenter",
    "kit.presenter.step": "Hakbang {n} sa {total}",
    "kit.presenter.announce": "Hakbang {n} sa {total}: {caption}",
    "kit.presenter.next": "Susunod na hakbang",
    "kit.presenter.back": "Nakaraang hakbang",
    "kit.presenter.hide": "Itago ang presenter bar",
    "kit.presenter.timerStart": "Simulan ang timer",
    "kit.presenter.timerPause": "I-pause ang timer",
    "kit.presenter.timerReset": "I-reset ang timer",
    "kit.presenter.elapsed": "Lumipas na oras",
    "kit.presenter.left": "{time} pa ang natitira",
    "kit.presenter.over": "Lampas nang {time}",
    "kit.presenter.keys": "→ susunod · ← balik · T timer · P bar · Esc itago",
    "kit.presenter.notesKeys": "→ susunod · ← balik · T timer",
    "kit.presenter.notesTitle": "Mga tala ng presenter",
    "kit.presenter.notes": "Mga tala ng tagapagsalita",
    "kit.presenter.noNotes": "Walang tala para sa hakbang na ito.",
    "kit.presenter.upNext": "Susunod",
    "kit.presenter.end": "Katapusan ng demo",
  },
} satisfies { en: Record<string, string>; war: Record<string, string>; fil: Record<string, string> };
